  name: TreeCutting
  main: fi.localghost.TreeCutting.TreeCutting
  version: 12.2A
  api-version: 1.20
  author: Mixerboy24 / LocalghostFI
  description: Enables quick tree felling
  commands:
    treecutting:
      description: §6Treecutting command
      usage: §6/treecutting §yversion